name: Build and Push Container

on:
  push:
    branches:
      - docker-image-build
  workflow_dispatch:    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Containers Development
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile
          target: bolt-ai-development   
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:development
            ${{ secrets.DOCKER_USERNAME }}/bolt-ai:development
          build-args: |
            --env-file .env.example

      # - name: Build and Push Containers Production
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     target: bolt-ai-production   
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:production
      #       ${{ secrets.DOCKER_USERNAME }}/bolt-ai:production
      #     build-args: |
      #       --env-file .env.example